### ISSUE TITLE
Running `grit config` with no config file causes panic

### ISSUE THREAD

**Issue by koden-km** [jmalloc/grit#15]
Fresh install of grit 0.2.1 and running `grit config` with no config file gave me this:
```
~: grit config
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/jmalloc/grit/src/grit.(*Config).normalizeClone(0xc420013c80, 0xc4200f1b40, 0x12, 0xc4200f1b53, 0xb)
	/home/travis/gopath/src/github.com/jmalloc/grit/src/grit/config.go:70 +0x1e4
github.com/jmalloc/grit/src/grit.(*Config).normalize(0xc420013c80, 0xc4200f1b40, 0x12, 0x12, 0x0)
	/home/travis/gopath/src/github.com/jmalloc/grit/src/grit/config.go:56 +0x43
github.com/jmalloc/grit/src/grit.LoadConfig(0xc4200f1b40, 0x1e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
	/home/travis/gopath/src/github.com/jmalloc/grit/src/grit/config.go:50 +0x443
main.loadConfig(0xc4200c28c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5, 0x151d38f)
	/home/travis/gopath/src/github.com/jmalloc/grit/src/cmd/grit/main.go:120 +0x9b
main.withConfig.func1(0xc4200c28c0, 0x0, 0xc4200c28c0)
	/home/travis/gopath/src/github.com/jmalloc/grit/src/cmd/grit/main.go:125 +0x49
github.com/jmalloc/grit/vendor/github.com/urfave/cli.HandleAction(0x148d600, 0xc420011f80, 0xc4200c28c0, 0xc420068700, 0x0)
	/home/travis/gopath/src/github.com/jmalloc/grit/vendor/github.com/urfave/cli/app.go:483 +0x10f
github.com/jmalloc/grit/vendor/github.com/urfave/cli.Command.Run(0x151e06a, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x152f842, 0x24, 0x0, ...)
	/home/travis/gopath/src/github.com/jmalloc/grit/vendor/github.com/urfave/cli/command.go:193 +0xb72
github.com/jmalloc/grit/vendor/github.com/urfave/cli.(*App).Run(0xc4200fe340, 0xc42000a1a0, 0x2, 0x2, 0x0, 0x0)
	/home/travis/gopath/src/github.com/jmalloc/grit/vendor/github.com/urfave/cli/app.go:250 +0x7d0
main.main()
	/home/travis/gopath/src/github.com/jmalloc/grit/src/cmd/grit/main.go:114 +0x8f1
```

**Comment by jmalloc** [comment]
Fixed in e96b940 (0.2.2 hotfix) and f006174 (master)
